sudo: false

services: couchdb

language:
- ruby
- python

rvm:
- 2.2.2

cache:
- bundler
- pip

install:
- pip install --user couchapp
- gem install poltergeist rspec
# Install traduxio
- cp spec/samples/the_lamp.json couchdb/the_lamp.json
- couchapp push couchdb http://localhost:5984/traduxio
#Load data
- spec/load_data.sh http://localhost:5984/traduxio

script:
- "rspec  spec/features/Search_concordance.rb
          spec/features/work_add.rb
          spec/features/Create_translation.rb
          spec/features/Compare_translations.rb
          spec/features/listworks.rb
          spec/features/Internationalization.rb
          spec/features/Set_license.rb"
